name: 'Markdown dead link checker'
description: 'This handy tool helps you maintain the integrity of your Markdown files by identifying broken links.'
branding:
  icon: 'external-link'
  color: 'blue'

inputs:
  config:
    description: 'Config toml file'
    required: false
    default: 'pyproject.toml'
  version:
    description: 'Version of package'
    required: false
    default: '0.6'
runs:
  using: 'composite'
  steps:
    - name: Install Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install md-dead-link-check
      run: pip install md-dead-link-check==${{ inputs.version }}
      shell: bash

    - name: (PR) Get all changed markdown files
      id: changed-markdown-files
      if: github.event_name == 'pull_request'
      uses: tj-actions/changed-files@v43
      with:
        files: |
            **.md

    - name: (PR) Check links
      if: github.event_name == 'pull_request'
      env:
        CHANGED_FILES: ${{ steps.changed-markdown-files.outputs.all_changed_files }}
      run: md-dead-link-check --hook ${CHANGED_FILES}
      shell: bash

    - name: Check all links
      if: github.event_name != 'pull_request'
      run: md-dead-link-check
      shell: bash
