name: 'Markdown dead link checker'
description: 'This handy tool helps you maintain the integrity of your Markdown files by identifying broken links.'
branding:
  icon: 'external-link'
  color: 'blue'

inputs:
  config:
    description: 'Config toml file'
    required: false
    default: 'pyproject.toml'
  version:
    description: 'Version of package'
    required: false
    default: '1.2.0'
  python_version:
    description: 'Python version'
    required: false
    default: '3.10'

runs:
  using: 'composite'
  steps:
    - name: Install Python
      uses: actions/setup-python@a26af69be951a213d495a4c3e4e4022e16d87065 # v5.6.0
      with:
        python-version: ${{ inputs.python_version }}

    - name: Install md-dead-link-check
      run: pip install md-dead-link-check==${{ inputs.version }}
      shell: bash

    - name: (PR) Get all changed markdown files
      id: changed-markdown-files
      if: github.event_name == 'pull_request'
      uses: tj-actions/changed-files@ed68ef82c095e0d48ec87eccea555d944a631a4c # v46.0.5
      with:
        files: |
            **.md

    - name: (PR) Check links
      if: github.event_name == 'pull_request'
      run: md-dead-link-check --config=${{ inputs.config }} --hook ${{ steps.changed-markdown-files.outputs.all_changed_files }}
      shell: bash

    - name: Check all links
      if: github.event_name != 'pull_request'
      run: md-dead-link-check --config=${{ inputs.config }}
      shell: bash
