name: 'Markdown dead link checker'
description: 'This handy tool helps you maintain the integrity of your Markdown files by identifying broken links.'
branding:
  icon: 'external-link'
  color: 'blue'

inputs:
  config:
    description: 'Config toml file'
    required: false
    default: 'pyproject.toml'
  version:
    description: 'Version of package'
    required: false
    default: '1.1.0'
  python_version:
    description: 'Python version'
    required: false
    default: '3.10'

runs:
  using: 'composite'
  steps:
    - name: Install Python
      uses: actions/setup-python@42375524e23c412d93fb67b49958b491fce71c38 # v5.4.0
      with:
        python-version: ${{ inputs.python_version }}

    - name: Install md-dead-link-check
      run: pip install md-dead-link-check==${{ inputs.version }}
      shell: bash

    - name: (PR) Get all changed markdown files
      id: changed-markdown-files
      if: github.event_name == 'pull_request'
      uses: tj-actions/changed-files@2f7c5bfce28377bc069a65ba478de0a74aa0ca32 # v46.0.1
      with:
        files: |
            **.md

    - name: (PR) Check links
      if: github.event_name == 'pull_request'
      run: md-dead-link-check --config=${{ inputs.config }} --hook ${{ steps.changed-markdown-files.outputs.all_changed_files }}
      shell: bash

    - name: Check all links
      if: github.event_name != 'pull_request'
      run: md-dead-link-check --config=${{ inputs.config }}
      shell: bash
