name: Linter

on:
  pull_request:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'
  push:
    branches:
      - main

jobs:
  pre-commit:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
      - uses: actions/setup-python@5fda3b95a4ea91299a34e894583c3862153e4b97 # v7.0.0
        with:
          python-version: "3.12"
      - name: Install pre-commit
        run: pip install pre-commit==3.2.2
      - name: Run pre-commit
        run: pre-commit run -a
      - name: Run try-repo
        run: pre-commit try-repo .
