name: Linter

on:
  pull_request:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'
  push:
    branches:
      - main

jobs:
  pre-commit:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - uses: actions/setup-python@ece7cb06caefa5fff74198d8649806c4678c61a1 # v6.3.0
        with:
          python-version: "3.12"
      - name: Install pre-commit
        run: pip install pre-commit==3.2.2
      - name: Run pre-commit
        run: pre-commit run -a
      - name: Run try-repo
        run: pre-commit try-repo .
