name: Validation

on:
  push:
    branches:
      - '*'
  pull_request:
    types:
      - opened
      - reopened
      - synchronize

jobs:
  pre-commit:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - name: Install pre-commit
        run: pip install pre-commit==3.2.2
      - name: Run pre-commit
        run: pre-commit run -a

  pytest:
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        python-version: ["3.8", "3.9", "3.10", "3.11", "3.12"]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install package
        run: pip install .[dev]
      - name: Pytest
        run: pytest tests -rfs -vv

  md-dead-link-check:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - uses: AlexanderDokuchaev/md-dead-link-check@main
        with:
          config: pyproject.toml
