name: Windows

on:
  pull_request:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'
  push:
    branches:
      - main
jobs:
  pytest:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - uses: actions/setup-python@a309ff8b426b58ec0e2a45f0f869d46889d02405 # v6.2.0
        with:
          python-version: "3.12"
      - name: Install package
        run: pip install .[dev]
      - name: Pytest
        run: pytest tests -rfs -vv
      - name: Run
        run: md-dead-link-check.exe --all
